### ISSUE TITLE
DVD catalog file named for my mountpoint

### ISSUE THREAD

**Issue by xtiansimon** [deadc0de6/gocatcli#9]
I'm SSH'd to a headless Debian box and using mount to mount a DVD.
After indexing `/mnt/dvd`, I have an index named, "dvd". But dvd was just the mountpoint for the contents of the dvd.

Now I mount my second dvd and gocatcli is asking, _"A storage with the name "dvd" already exists, update it? [y/N]"_
I don't think that's what I want to do. I want the catalog to list each dvd individually.

Can I rename `dvd` to something else? 
I thought to try the intuitive `mv` and `rename` commands, but they don't work. 

And maybe I don't understand the paradigm. I've used the command `gocatcli index` on three different DVDs (now uniquely named), but when I run the command `gocatcli ls`, I only see the last disk??

**Comment by deadc0de6** [comment]
The `index` command has an optional argument that allows you to specify the name of the storage when indexing:
```
gocatcli index <path> [<name>] [flags]
```
You can get more options by running `gocatcli index --help`.

What you could do is indexing each dvd with a name, for example
```bash
## mount dvd 1
$ gocatcli index /mnt/dvd dvd1
## umount dvd 1 and mount dvd 2
$ gocatcli index /mnt/dvd dvd2
```
You would then end up with two storages `dvd1` and `dvd2`.

`gocatcli` does not provide an option to rename storage but you can always directly edit the catalog file (per default `gocatcli.catalog`) if you need to.

**Comment by deadc0de6** [comment]
`gocatcli` indexes files in a tree-like structure. There are different types of entry in a catalog:

* `top node`: this is the root of the hierarchy
* `storage node`: this represents an indexed storage (a DVD, an external hard drive, an USB drive, some arbitrary directory, etc).
* `dir node`: this is a directory
* `file node`: this is a file
* `archive node`: this is an archive file (tar, zip, etc)
* `archived node`: this is a file contained in an archive 

Each filesystem/directory that you index using the `index` command ends up as a storage entry in the catalog. If you don't provide a name, the basename of its path will be used (this is why you ended up with `dvd` as a storage name since the path was `/mnt/dvd`). By providing a name during indexation you create different storage.

All operations are done on the entire catalog (all storages) unless you provide a specific path.

I'll add this information to the doc.
Does that answer your question?
